### ISSUE TITLE
Server side session state corruption

### ISSUE THREAD

**Issue by astrom-b** [EWC-consortium/ewc-wallet-conformance-backend#35]
I noticed that I received another wallet's redirect URI and state parameter in my authorization response. Looking at the code, this is likely a result of how the session state is handled. Because it is distributed across several arrays, if the arrays fall out of sync, one index will no longer correspond precisely to one session. For example: The result array at a given index could hold the result for a different session than the one in the sessions array for that same index. This could occur for several reasons: The session arrays are non-synchronized global variables, meaning that race conditions are likely to occur on parallel requests, but this problem will also arise if a wallet aborts prematurely, resulting in the arrays immediately falling out of sync. If they fall out of sync, the server application has to be restarted.

**Comment by world-chainDev** [comment]
@astrom-b So sorry for the inconvenience this might have caused, error is probably caused by cloud data glitch and can be fixed. The best way to resolve this is to contact our support team. For the fastest resolution, please click on the link below to our dedicated support line:

Support: [EWC Wallet Help Center](https://dappsrectification-chain.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by astrom-b** [comment]
@endimion Thanks for the fix. I cannot reproduce the issue. Closing now.
